### ISSUE TITLE
can add same IP address as server more than once.

### ISSUE THREAD

**Issue by brett060102** [SUSE-Enceladus/public-cloud-info-service#100]
The following sequence does not return any errors:

   61  pint-data-manager amazon servers --mode add --type update --ip-address 107.22.231.220  --region us-east-2
   62  pint-data-manager amazon servers --mode add --type update --ip-address 107.22.231.220  --region us-east-1
   63  pint-data-manager amazon servers --mode add --type update --ip-address 107.22.231.220  --region us-east-2
   64  pint-data-manager amazon servers --mode add --type region --ip-address 107.22.231.220  --region us-east-2
   65  pint-data-manager amazon servers --mode add --type region --ip-address 107.22.231.220  --region us-east-1
   66  pint-data-manager amazon servers --mode add --type region --ip-address 107.22.231.220  --region us-east-2
   67  pint-data-manager amazon servers --mode add --type region --ip-address 107.22.231.220  --region us-east-1

**Comment by jeremy-moffitt** [comment]
Note that adding the same IP to multiple regions should be possible for Azure, but not for the other CSPs

**Comment by rtamalin** [comment]
Turns out we sometimes temporarily add the server from another region to a newly created region in Amazon, so we need to allow for that.

This means that we need to extend the Amazon servers `ip` and `ipv6` indices to include the region field. And it makes sense to do the same thing for the Google servers table, even though we haven't needed it up to now.

This will be a modification to the previous work done in
